Introduce impersonation support
neo4j/neo4j-java-driver pull request #1028
Opened 2021-10-06 12:36 UTC by injectives

This update brings support for the new impersonation feature. This feature allows creating sessions with impersonated user, including using default database of impersonated user.

Tests: https://github.com/neo4j-drivers/testkit/pull/266

2021-10-06 14:46 UTC, michael-simons requested changes
First quick look.

2021-10-06 14:46 UTC, michael-simons commented on driver/src/main/java/org/neo4j/driver/internal/ImpersonationUtil.java
> +            " over Bolt 4.4 version or above when using impersonation feature";
```suggestion
            " over Bolt version 4.4 or above when using impersonation feature";
```

2021-10-11 18:53 UTC, gjmwoods commented on driver/src/main/java/org/neo4j/driver/SessionConfig.java
> +    public Optional<String> impersonatedUser()
javadoc pls

2021-10-11 18:53 UTC, gjmwoods commented on driver/src/main/java/org/neo4j/driver/SessionConfig.java
> +         * The driver must have the necessary permissions to impersonate and run queries as the impersonated user.
```suggestion
         * The user provided to the driver on creation must have the necessary permissions to impersonate and run queries as the impersonated user.
```
Something like that

2021-10-11 18:53 UTC, gjmwoods commented on driver/src/main/java/org/neo4j/driver/internal/async/ImmutableConnectionContext.java
> +    public ImmutableConnectionContext( DatabaseName databaseName, Bookmark bookmark, AccessMode mode, String impersonatedUser )
`impersonatedUser` looks to be always null, can be removed from constructor

2021-10-11 18:53 UTC, gjmwoods commented on driver/src/main/java/org/neo4j/driver/internal/util/ServerVersion.java
> +    public static final ServerVersion v4_4_0 = new ServerVersion( NEO4J_PRODUCT, 4, 4, 0 );
one for late but we're missing 4.3 here

2021-10-11 19:31 UTC, injectives commented on driver/src/main/java/org/neo4j/driver/internal/util/ServerVersion.java
> +    public static final ServerVersion v4_4_0 = new ServerVersion( NEO4J_PRODUCT, 4, 4, 0 );
I noticed, but did not add because I was not going to use it.
However, I have just noticed that the `fromBoltProtocolVersion` method should be updated.

2021-10-11 19:33 UTC, injectives commented on driver/src/main/java/org/neo4j/driver/internal/async/ImmutableConnectionContext.java
> +    public ImmutableConnectionContext( DatabaseName databaseName, Bookmark bookmark, AccessMode mode, String impersonatedUser )
Updated.

2021-10-11 19:48 UTC, injectives commented on driver/src/main/java/org/neo4j/driver/SessionConfig.java
> +         * The driver must have the necessary permissions to impersonate and run queries as the impersonated user.
Please check this statement again.

2021-10-11 23:27 UTC, injectives commented on driver/src/main/java/org/neo4j/driver/SessionConfig.java
> +    public Optional<String> impersonatedUser()
Added.

2021-10-12 06:01 UTC, gjmwoods approved these changes
LGTM!

2021-10-12 09:11 UTC, injectives commented
@michael-simons, this PR has been reviewed by @gjmwoods. We are going to merge this now to get the first alpha released.

2021-10-12 09:11 UTC, merged