Fix more test that fail due to cypher deprecation removals
neo4j/neo4j-java-driver pull request #1167
Opened 2022-03-01 11:49 UTC by gjmwoods

2022-03-03 10:55 UTC, fbiville approved these changes

2022-03-03 10:56 UTC, fbiville requested changes

2022-03-03 10:56 UTC, fbiville commented on driver/src/test/java/org/neo4j/driver/integration/ConnectionHandlingIT.java
> +            session.run( "CREATE CONSTRAINT FOR (book:Library) REQUIRE book.isbn IS NOT NULL" );
this needs to depend per neo4j version
(this syntax is valid with 4.4 and 5.0 but not earlier)

2022-03-07 10:09 UTC, michael-simons requested changes

2022-03-07 10:09 UTC, michael-simons commented on driver/src/test/java/org/neo4j/driver/util/DatabaseExtension.java
>              String protocolVersion = session.readTransaction( tx -> tx.run( "RETURN 1" ).consume().server().protocolVersion() );
I would rather use 

```
CALL dbms.components() YIELD versions, edition 
RETURN 'Neo4j/' + versions[0] AS version, edition
```

bolt protocol depends on what server and client negotiated.

2022-03-08 14:28 UTC, michael-simons requested changes
Sorry for the nitpicking on wording.

2022-03-08 14:28 UTC, michael-simons commented on driver/src/test/java/org/neo4j/driver/util/DatabaseExtension.java
> +            String protocolVersion = session.readTransaction( tx -> tx.run( "CALL dbms.components() YIELD versions " +
```suggestion
            String neo4jVersion = session.readTransaction( tx -> tx.run( "CALL dbms.components() YIELD versions " +
```

2022-03-08 14:28 UTC, michael-simons commented on driver/src/test/java/org/neo4j/driver/util/DatabaseExtension.java
>              String[] versions = protocolVersion.split( "\\." );
```suggestion
            String[] versions = neo4jVersion.split( "\\." );
```

2022-03-23 11:54 UTC, michael-simons approved these changes
Thanks.

2022-03-23 12:30 UTC, injectives commented on testkit-backend/src/main/java/neo4j/org/testkit/backend/messages/requests/SessionWriteTransaction.java
> +                if ( workThrowable instanceof FrontendError )
Is this duplicate of the block below?

2022-03-23 12:30 UTC, injectives commented on testkit-backend/src/main/java/neo4j/org/testkit/backend/messages/requests/SessionReadTransaction.java
> +                if ( workThrowable instanceof FrontendError )
Is this duplicate of the block below?

2022-03-23 15:29 UTC, merged