Auth
neo4j/neo4j-java-driver pull request #1380
Opened 2023-02-20 15:14 UTC by injectives

2023-03-02 19:07 UTC, injectives commented
Resolves: #1371

2023-03-03 10:12 UTC, michael-simons requested changes
This is one of the best and complete PR descriptions I have read in a while, thanks for going the extra mile here, @injectives 

In general, I do like the API solution. The container format would not be my preferred solution (As I mentioned earlier, I would rather `TemporalAuthToken extends AuthToken` and do proper type checks in the implementation), but if you prefer it that way, I can live with it.

What I don't like is the naming. `Temporal` can be anything. While it is better than `Renewable`, it doesn't capture the essence of wrt it expires. It is a mouthful, but `ExpiringToken` or `TokenWIthExpirationDate` would give a very clear indication of what this actually is.

2023-03-07 15:21 UTC, gjmwoods reviewed
Also apreciate the detailed PR comment, especially with how much the ADR has grown in size.

Just some minor initial comments on the surface parts.

2023-03-07 15:21 UTC, gjmwoods commented on driver/src/main/java/org/neo4j/driver/internal/InternalDriver.java
> +    public boolean verifyAuthentication(AuthToken authToken) {
`RETURN 1` wont work against `system`. Maybe we pick something like `SHOW SERVERS`?

2023-03-07 15:21 UTC, gjmwoods commented on driver/clirr-ignored-differences.xml
> +
Guess clirr excludes `GraphDatabase`

2023-03-07 15:21 UTC, gjmwoods commented on driver/src/main/java/org/neo4j/driver/AuthTokenManagers.java
> +         * @param expirationTimestamp the expiration timestamp
```suggestion
         * @param expirationUTCTimestamp the UTC expiration timestamp
```

2023-03-09 12:24 UTC, ikwattro commented on driver/src/main/java/org/neo4j/driver/internal/InternalDriver.java
> +    public boolean verifyAuthentication(AuthToken authToken) {
We use `CALL db.ping()` for the same purpose.

2023-03-09 21:33 UTC, injectives commented on driver/clirr-ignored-differences.xml
> +
It probably does not count `static` methods addition as incompatibility. A removal of method would trigger it.

2023-04-03 15:09 UTC, injectives commented
> What I don't like is the naming. `Temporal` can be anything. While it is better than `Renewable`, it doesn't capture the essence of wrt it expires. It is a mouthful, but `ExpiringToken` or `TokenWIthExpirationDate` would give a very clear indication of what this actually is.

@michael-simons, thanks a lot for the review and for the kind comment.

As you might be aware, there has been a team discussion and it has been decided to go with `AuthTokenAndExpiration`, which hopefully is a better name.

2023-04-03 15:10 UTC, injectives commented
> Also apreciate the detailed PR comment, especially with how much the ADR has grown in size.
> 
> Just some minor initial comments on the surface parts.

@gjmwoods many thanks for the review and for the kind comment.

The comments have been addressed.

2023-04-12 12:08 UTC, gjmwoods approved these changes

2023-04-12 13:29 UTC, merged