Resolve DNS to IP & IPv6 address support
neo4j/neo4j-java-driver pull request #332
Opened 2017-03-10 15:57 UTC by zhenlineo

2017-03-16 14:00 UTC, lutovich requested changes
@zhenlineo review round completed. Do you think it is possible to add a boltkit test with some fake resolver to verify this feature end to end?

2017-03-16 14:00 UTC, lutovich commented on driver/src/main/java/org/neo4j/driver/internal/cluster/ClusterRoutingTable.java
> +        routers.remove( address );
This `#forget()` method is also called on connection errors. Do we really want to drop routers here? I'd vote for not changing this and keeping `#removeRouter()`.

2017-03-16 14:00 UTC, lutovich commented on driver/src/main/java/org/neo4j/driver/internal/cluster/DnsResolver.java
> +public interface DnsResolver
Could we maybe have `HostNameResolver` interface and then `DnsResolver` as it's implementation?

2017-03-16 14:00 UTC, lutovich commented on driver/src/main/java/org/neo4j/driver/internal/cluster/DnsResolver.java
> +                Set<BoltServerAddress> addresses = new HashSet<>( ipAddresses.length );
Specified like this initial capacity might still cause `HashSet` to resize because of default load factor or 0.75. Maybe not bother with initial size at all? :)

2017-03-16 14:00 UTC, lutovich commented on driver/src/main/java/org/neo4j/driver/internal/cluster/DnsResolver.java
> +                throw new ServiceUnavailableException(
What will happen if seed uri is already an IP address? Will `UnknownHostException` be thrown?
What do you think about just logging failure here and returning `Collections.singleton(initialRouter)`?

2017-03-16 14:00 UTC, lutovich commented on driver/src/main/java/org/neo4j/driver/internal/cluster/Rediscovery.java
> +        Set<BoltServerAddress> triedServers = new HashSet<>( size );
`HashSet`'s initial capacity might be tricky here as well.

2017-03-16 14:00 UTC, lutovich commented on driver/src/test/java/org/neo4j/driver/internal/cluster/RediscoveryTest.java
> +    private static DnsResolver directMapProvider = new DnsResolver()
Maybe introduce a `private static class` for this or move it to the top of the class? It is just a bit strange to see field in the middle of the class.

2017-03-16 14:00 UTC, lutovich commented on driver/src/test/java/org/neo4j/driver/internal/cluster/RediscoveryTest.java
> +            Set<BoltServerAddress> directMap = new HashSet<>( 1 );
Could probably use `Collections.singleton( initialRouter )` here

2017-03-16 15:54 UTC, zhenlineo commented on driver/src/main/java/org/neo4j/driver/internal/cluster/ClusterRoutingTable.java
> +        routers.remove( address );
What's the point to keep in routing table? they were there to protect from running out of routers. Now we no longer have the problem with dns

2017-03-17 09:08 UTC, zhenlineo commented on driver/src/main/java/org/neo4j/driver/internal/cluster/DnsResolver.java
> +                throw new ServiceUnavailableException(
IP to IP is not a problem, the test include using `127.0.0.1`

2017-03-17 09:15 UTC, zhenlineo commented
@lutovich All boltkit tests that creates a real driver already goes via DnsResolver

2017-03-17 09:37 UTC, zhenlineo commented on driver/src/test/java/org/neo4j/driver/internal/cluster/RediscoveryTest.java
> +            Set<BoltServerAddress> directMap = new HashSet<>( 1 );
No, I cannot return any singlention set as it does not support `removeAll` method

2017-03-21 15:17 UTC, lutovich approved these changes

2017-03-22 09:22 UTC, merged