Metrics
neo4j/neo4j-java-driver pull request #556
Opened 2019-01-21 11:26 UTC by zhenlineo

Exposing connection pool metrics for monitoring purpose.

2019-01-21 11:27 UTC, zhenlineo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Driver statistics a.k.a. ConnectionPoolMetrics](https://trello.com/c/WHF1GlIj/352-driver-statistics-aka-connectionpoolmetrics)

2019-01-22 11:54 UTC, ali-ince requested changes

2019-01-22 11:54 UTC, ali-ince commented on driver/src/main/java/org/neo4j/driver/v1/Config.java
> +     * Logging metricsTracker
wrong find/replace? :)

2019-01-22 11:54 UTC, ali-ince commented on driver/src/main/java/org/neo4j/driver/v1/ConnectionPoolMetrics.java
> +     * The amount of channels that are currently in-use (borrowed out of the pool).
maybe use `connections` instead of the driver internal concept `channels`?

2019-01-22 11:54 UTC, ali-ince commented on driver/src/main/java/org/neo4j/driver/internal/metrics/ListenerEvent.java
> +    void start( long currentTime );
Wdyt if we leave the interface as earlier but pass the `Clock` instance to the `TimeRecorderListenerEvent`?

2019-01-29 09:19 UTC, ali-ince approved these changes

2019-01-29 09:19 UTC, merged